services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Porta AMQP (Python/Go usam essa)
      - "15672:15672" # Painel web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  python-producer:
    build: ./python-producer
    depends_on:
      - rabbitmq

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nest-api:
    build: ./nest-api
    container_name: nest-api
    ports:
      - "3000:3000"
    env_file:
      - ./nest-api/.env
    depends_on:
      - mongo

  go-worker:
    build: ./go-worker
    env_file:
      - ./go-worker/.env
    depends_on:
      - rabbitmq
      - nest-api

volumes:
  mongo-data:
